### PR TITLE
Solves the import conflict

### PR DESCRIPTION
**Pull request by abdallah1097**
Imports give error, this is because code uses absolute paths from the project root. However, __main__.py must be outside of "minesweeper" directory to be able to "from minesweeper.game.Game import Game

Error was:
```bash
Abdallah@DESKTOP-G6QENGL MINGW64 /d/Work/GitHub Contributions/Minesweeper-Python-Tkinter (solving-relative-imports)
$ python minesweeper/__main__.py
Traceback (most recent call last):
  File "D:\Work\GitHub Contributions\Minesweeper-Python-Tkinter\minesweeper\__main__.py", line 2, in <module>
    from minesweeper.game.Game import Game
ModuleNotFoundError: No module named 'minesweeper'
(minesweeper)
```

For more details please check [this](https://towardsdatascience.com/how-to-fix-modulenotfounderror-and-importerror-248ce5b69b1c?gi=8b802623bf1c)

### CODE REVIEW

**Comment by SashaKryzh** [comment]
@abdallah1097 Hello! This is my first big python project. I was structuring files referring to [this guide](https://dev.to/codemouse92/dead-simple-python-project-structure-and-imports-38c6). The idea was to run the program from root with `python -m minesweeper` command. It works perfectly in PyCharm. I figured out that this is because It automatically adds content roots to PYTHONPATH. Maybe you should do it too as explained in the [tutorial you provided](https://towardsdatascience.com/how-to-fix-modulenotfounderror-and-importerror-248ce5b69b1c).

Could you please tell me how am I supposed to run the program in your version? And what approach is better?

**Comment by abdallah1097** [comment]
> am

@SashaKryzh The pull request contains the solution :D you can merge it, simply I changed the main.py file

**Comment by SashaKryzh** [comment]
@abdallah1097 Yeah, I looked at it. But you just moved the `__main__.py` from minesweeper to the root. And this is not my initial idea, because now you should run the game with `python __main__.py` and not with `python -m minesweeper`.
I have added `python -m minesweeper` to the README.md so no one will be confused. Does this solve the problem or I get something wrong?

**Comment by abdallah1097** [comment]
> with

Yeah this solves the problem, readme.md would have clarified this :D

**Pull request closed without merging**
